Repository AutoeverInsideMovie/Insidemovie-AI, pull requests merged in 2025-07, with the labels that each got.

#7 Feat/#4
  .gitattributes
  config.py
  const.py
  data/emotion_data.csv
  data/emotions_augmented_0712.csv
  db.py
  main.py
  models/0711_kobert_7_emotion_model/config.json
  models/0711_kobert_7_emotion_model/model.safetensors
  models/0711_kobert_7_emotion_model/special_tokens_map.json
  models/0711_kobert_7_emotion_model/spiece.model
  models/0711_kobert_7_emotion_model/tokenizer_config.json
  models/0712_kobert_5_emotion_model/config.json
  models/0712_kobert_5_emotion_model/model.safetensors
  models/0712_kobert_5_emotion_model/special_tokens_map.json
  models/0712_kobert_5_emotion_model/spiece.model
  models/0712_kobert_5_emotion_model/tokenizer_config.json
  models/0712_kobert_6_emotion_model/config.json
  models/0712_kobert_6_emotion_model/model.safetensors
  models/0712_kobert_6_emotion_model/special_tokens_map.json
  models/0712_kobert_6_emotion_model/spiece.model
  models/0712_kobert_6_emotion_model/tokenizer_config.json
  routers/home.py
  routers/predict.py
  schemas.py
  services/prediction.py
Labels: FEAT

#9 [REFAC] 대용량 파일 정리
  data/emotion_data.csv
  data/emotions_augmented_0712.csv
  models/0711_kobert_7_emotion_model/config.json
  models/0711_kobert_7_emotion_model/model.safetensors
  models/0711_kobert_7_emotion_model/special_tokens_map.json
  models/0711_kobert_7_emotion_model/spiece.model
  models/0711_kobert_7_emotion_model/tokenizer_config.json
  models/0712_kobert_6_emotion_model/config.json
  models/0712_kobert_6_emotion_model/model.safetensors
  models/0712_kobert_6_emotion_model/special_tokens_map.json
  models/0712_kobert_6_emotion_model/spiece.model
  models/0712_kobert_6_emotion_model/tokenizer_config.json
  services/prediction.py
Labels: REFAC

#11 Feat/#10 모델 입력값 문장 단위로 분리 및 토크나이저 설정 수정
  routers/predict.py
  services/prediction.py
Labels: FEAT

#13 Refac/#12 가상 환경 설치 및 필수 패키지 설치 가이드 제공
  README.md
  environment.yml
Labels: SETTING

#17 Refac/#16 감정 라벨 수정 완료
  const.py
Labels: REFAC

#19 Dev
  Dockerfile
  config.py
  const.py
  db.py
  models/0712_kobert_5_emotion_model/model.safetensors
  models/0717_kobert_5_emotion_model/config.json
  models/0717_kobert_5_emotion_model/model.safetensors
  models/0717_kobert_5_emotion_model/special_tokens_map.json
  models/0717_kobert_5_emotion_model/spiece.model
  models/0717_kobert_5_emotion_model/tokenizer_config.json
  routers/predict.py
  schemas.py
Labels: FIX

#21 [CHORE] 감정 예측 엔드포인트 정리 및 LABELS 상수 정리
  config.py
  const.py
  main.py
  routers/home.py
  routers/predict.py
  routers/review.py
  schemas.py
  services/prediction.py
Labels: REFAC, FEAT
